apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: money-tracker-api
  name: money-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-tracker-api
  template:
    metadata:
      labels:
        app: money-tracker-api
    spec:
      containers:
        - name: money-tracker-api
          image: kamarkaka4/money-tracker-api:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: 'postgres'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'money_tracker'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: API_PORT
              value: '8080'
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: money-tracker-api
  labels:
    app: money-tracker-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: money-tracker-api
