apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: "echo -n <username> | base64"
  password: "echo -n <password> | base64"
  pgpass_app_updater: "echo -n <host:port:dbname:username:password> | base64"
  pgpass_money_tracker: "echo -n <host:port:dbname:username:password> | base64"
